### ISSUE TITLE
魊影/异鱼显示问题

### ISSUE THREAD

**Issue by qingyli** [mikualpha/master-duel-chinese-switch#1]
可能是只有我有问题？魊在我游戏里显示的是框框。我看了card.json里没这张卡，只有card_api_cache.json里有，可能和这个有关系？电脑本身是可以打出魊这个字的。

**Comment by mikualpha** [comment]
目前看是少部分正常，大部分不正常(包括我的也不正常233
但是需要先看为什么会导致部分正常部分不正常的情况，没弄清楚之前不敢乱动

可以尝试找这两个字体安装一下看看会不会变正常（没尝试过，有小概率可以）
- 方正悠黑简体_509R
- 方正悠黑简体_512R

不行我就后面发个pre-release……

**Comment by mikualpha** [comment]
已在[v1.5.1-Beta](https://github.com/mikualpha/master-duel-chinese-switch/releases/tag/v1.5.1-beta)中处理。
