### ISSUE TITLE
[有个问题想请教下]关于查卡API ygocdb 

### ISSUE THREAD

**Issue by IIceBreakker** [mikualpha/master-duel-chinese-switch#11]
**想自己改下换个API**
我这里的网络基本访问不了ygocdb，所以想请问下有啥稳定的API可以替换的吗，想自己改一下，谢谢

**Comment by mikualpha** [comment]
这个问题可能需要去问原作者(这边本质上也只是维护一个分支而已)，API一直保持原样没有更改过

小建议：可以考虑在HTTP协议请求处自己加HTTP代理来解决问题
