### ISSUE TITLE
Win11 exe闪退并自动删除 源代码typing error

### ISSUE THREAD

**Issue by shyDaniel** [mikualpha/master-duel-chinese-switch#12]
在b站 本repo的issues 甚至nga 都逛了一圈 发现没有人跟我有相同的问题 觉得有点匪夷所思 所以想发一个单独的issues 

---------------------------------------------------

Win11 不知道是不是系统的问题 点击exe有如下报错，同时会短暂生成一个tmp文件然后exe会自动删除
往下尝试了其他的release 一直到1.4.1 都是同样的问题 没有再尝试下面的release了

![Screenshot 2023-10-12 114154](https://github.com/mikualpha/master-duel-chinese-switch/assets/44783745/c41604b6-98b0-475f-9d56-7874381841be)

尝试过删除localdata然后重新下载缓存 没有解决问题

然后尝试直接运行source code，结果有很多 `'type' object is not subscriptable` 的报错，错误原因几乎都类似于 `list["a"]`， 我需要手动 `from typing import List, Dict` 然后改成 `List["a"]` 才能解决这个

解决了以后运行`flet run interface.py`，有这个报错 

`(flet:387): Gdk-CRITICAL **: 11:06:26.956: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed`

不清楚和exe打不开是不是同一个原因，总之无法打开gui

然后尝试运行 `python3 index.py`，在修改了`index.py`里的游戏路径以后在翻译步骤出现报错

```
安装中...
提取中
解包中
轮询密钥中
解密中
处理中
翻译中
unsupported operand type(s) for |: '_TypedDictMeta' and 'NoneType'
unsupported operand type(s) for |: '_TypedDictMeta' and 'NoneType'
失败
```
这貌似是个typing的version问题，把 `translate.py` 的line157改成 `Optional[CardRawDataItem]` 且 `from typing import Optional` 解决了这个问题

然后重新跑就成功了，然后把localdata内容删了好几次，又重新跑了几次游戏内成功更新了
```
安装中...
提取中
解包中
轮询密钥中
解密中
处理中
翻译中
WARN: Can't find 恐啡肽骇龙衍生物
WARN: Can't find G魔像衍生物
WARN: Can't find 幻耀衍生物
WARN: Can't find 阴魂怒吼鲑衍生物
WARN: Can't find 龙衍生物
WARN: Can't find 黑兽衍生物
WARN: Can't find 白兽衍生物
WARN: Can't find 海造贼衍生物
WARN: Can't find 宝贝螳螂衍生物
WARN: Can't find 蛇眼炎燐
WARN: Can't find 荷鲁斯之黑炎神
WARN: Can't find 肃声之祈祷者 律
WARN: Can't find 尤贝尔－“永恒爱守”
WARN: Can't find 威风魔灵・麒龙
100%|███████████████████████████████████████████████████████████████████████████| 12223/12223 [00:06<00:00, 1854.85it/s]
加密中
打包中
覆写中
成功
翻译成功！
```

**Comment by mikualpha** [comment]
`You may not have the appropriate **permissions** to access the item.`
可能是权限问题，可以尝试换个目录、用管理员权限执行(因为需要往`Temp`和`AppData`目录写东西，请保证有这俩目录的写入权限)。当然从文件被自删除来看也有可能是杀软的问题，可以关掉杀软再试。

至于`typing`相关的报错，可能是Python版本不对，本项目编译要求的Python版本是3.10以上。(我怎么记得刚开始摸这个项目的时候也有过类似问题，但是具体解决方式忘了= =)
