### ISSUE TITLE
[BUG] “蛇眼梣树灵”的“梣”字无法显示

### ISSUE THREAD

**Issue by MinYXn** [mikualpha/master-duel-chinese-switch#14]
**BUG描述**
“蛇眼梣树灵”的“梣”字无法显示
和上次“魊影”的bug相同，可能又需要字形修复了

**截图**
![image](https://github.com/mikualpha/master-duel-chinese-switch/assets/113080762/58a563dc-f73d-45eb-96a8-a6e8e1d9340e)

**系统及软件版本**
补丁版本1.7.1

**Comment by mikualpha** [comment]
过年回家没开发环境，到下次更新一起弄吧……
而且[上游数据源](https://ygocdb.com/)炸了，等上游修复先。

**Comment by mikualpha** [comment]
已在 [Release v1.7.2](https://github.com/mikualpha/master-duel-chinese-switch/releases/tag/v1.7.2) 中处理。
