### ISSUE TITLE
[Feature] 希望提供安卓端的翻译安装方式

### ISSUE THREAD

**Issue by MinYXn** [mikualpha/master-duel-chinese-switch#15]
确实还是挺需要的）

**Comment by mikualpha** [comment]
是有ROOT权限的设备？

**Comment by mikualpha** [comment]
写了个简单的，见[Android系统使用方式(Beta)](https://github.com/mikualpha/master-duel-chinese-switch/wiki/Android%E7%B3%BB%E7%BB%9F%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F(Beta))。

**Comment by MinYXn** [comment]
十分感谢
