### ISSUE TITLE
[BUG] 魊影系列的卡翻译和百鸽中的不一致

### ISSUE THREAD

**Issue by 1825265352** [mikualpha/master-duel-chinese-switch#16]
**BUG描述**

魊影系列的卡由于是TCG先发售的，所以效果栏里的部分翻译术语、格式和OCG这边有点不一样。魊影系列O化后，百鸽那边已经改成OCG的翻译术语、格式了（https://ygocdb.com/card/3137279）。
我在想是不是百鸽那边更新了数据，而本补丁对于已存在的卡片数据没有进行同步更新，不知道大佬有没有时间看一下。

**截图**
![image](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/05f6009f-6e15-4d2d-b82c-e2e347d0c223)
![image](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/6b506f54-7f84-4949-a4c9-7b6e1c2bd94b)

**系统及软件版本**
win10 22H2  补丁版本：1.7.2

**Comment by mikualpha** [comment]
是卡片缓存的问题，有空会做一版刷新后的。

**Comment by mikualpha** [comment]
已在 [Release v1.7.3](https://github.com/mikualpha/master-duel-chinese-switch/releases/tag/v1.7.3) 中处理。
