### ISSUE TITLE
[BUG] 邪恶★双子克星 翻译版本错误

### ISSUE THREAD

**Issue by lolbob** [mikualpha/master-duel-chinese-switch#17]
**BUG描述**

游戏中的这张卡不知道为何是是CNOCG的版本。。

其他双子卡我也都看了下，是正常的NW版本，只有这一张卡有问题。

NW版本如下
https://ygocdb.com/card/93672138

**截图**

游戏中如下

![masterduel_sSEt7suxIF](https://github.com/mikualpha/master-duel-chinese-switch/assets/5314949/c1cbec5a-8021-498a-97de-8d97e0f918a9)

补丁版本1.8.0

**Comment by mikualpha** [comment]
主要还是翻译版本管理太难了，尤其现在卡越整越多= =
等有空的时候想想翻译文本怎么刷合适再来处理……

**Comment by lolbob** [comment]
> 主要还是翻译版本管理太难了，尤其现在卡越整越多= = 等有空的时候想想翻译文本怎么刷合适再来处理……

我又去看了下， 这应该是百鸽那边的API有问题了，我看了下OUROCG那里也是用的白鸽API抓的NW翻译也是只有这一个双子翻译是错误的。

所以如果太麻烦就不用修了，百鸽那边怎么发信息啊，我主站找了一圈没看到在哪能联系……mercury233的github上也没看到百鸽。。

**Comment by mikualpha** [comment]
已在[v1.8.1](https://github.com/mikualpha/master-duel-chinese-switch/releases/tag/v1.8.1)中修复。
