### ISSUE TITLE
[BUG] 部分卡片发动效果后不显示已发动提示的✔

### ISSUE THREAD

**Issue by 1825265352** [mikualpha/master-duel-chinese-switch#18]
**BUG描述**
部分卡片正常发动后，虽然卡图右侧有提示已经发动了效果，但是文本框内并未显示发动的是几效果。正常情况下在发动效果后，文本框内会在数字①②③前面✔，部分卡片未显示✔提示。目前发现的会出现此问题的卡片有“增殖的g”、“灰流丽”、“解码语者·炽热之魂”。

**截图**
对比图中前面的是采用社区翻译的，后是采用游戏内简体中文翻译的
![g1](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/ac0ca106-0d21-472b-9896-e32fabdbb6b9)
![g2](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/2bc34be2-cc41-4e74-a97e-2817af43e743)
![灰1](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/94dbb387-7513-4273-923b-0ef80770c242)
![灰2](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/8396361e-2cb9-4d01-93fa-86aa85bfefad)
![火码1](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/853c448f-23b4-4941-bd1f-4edc455e28f0)
![火码2](https://github.com/mikualpha/master-duel-chinese-switch/assets/145309847/0942b363-2316-4ebc-868d-b2457e366130)

**系统及软件版本**
操作系统版本：win1022H2
所使用的补丁版本:v1.8.0

**Comment by mikualpha** [comment]
共同点应该是效果文本里带有字符"●"。
初步猜测应该是换行符或者其它特殊字符导致的，抽空看看，但不保证可以修复。
毕竟主要还是需要让翻译可读性高。

**Comment by 1825265352** [comment]
> 共同点应该是效果文本里带有字符"●"。 初步猜测应该是换行符或者其它特殊字符导致的，抽空看看，但不保证可以修复。 毕竟主要还是需要让翻译可读性高。

好的，感谢大佬。
其他两张卡的nw翻译和游戏官方翻译都是包含字符"●"，但是我发现增殖的g的效果文本是没有字符"●"的，官方翻译中增殖的z效果文本内才有字符"●"。

**Comment by mikualpha** [comment]
![image](https://github.com/mikualpha/master-duel-chinese-switch/assets/24711249/0401a403-cd91-4d95-9043-d7f8a75beb84)

已在[v1.8.1](https://github.com/mikualpha/master-duel-chinese-switch/releases/tag/v1.8.1)中修复。
