### ISSUE TITLE
[BUG] 魔法陷阱卡种类图标错位，部分卡片文本错位

### ISSUE THREAD

**Issue by ElapseRecall** [mikualpha/master-duel-chinese-switch#19]
### *BUG描述*

一开始觉得是文本量大导致的问题，找了张文本量差不多的同类型卡，发现并没有溢出问题，陷阱卡好像也没有溢出的情况，但是这个图标错位都存在。

### *截图*

|速攻魔法卡_1|速攻魔法卡_2|反击陷阱卡|
|---|---|---|
|![p1](https://github.com/user-attachments/assets/af3a2bdc-8479-4827-b569-443c8cfa7057)|![p2](https://github.com/user-attachments/assets/04cdc418-85ef-4919-bff0-bd6c9358b3f0)|![p3](https://github.com/user-attachments/assets/c22d4e3b-bb3f-45f8-a179-b9bb02ed4ddd)|

### *系统及软件版本*

软件版本为：v1.8.1

|系统信息|
|---|
|![info](https://github.com/user-attachments/assets/5c6c09d2-f622-4c5b-b250-bdf3394070ef)|

**Comment by mikualpha** [comment]
应该是字间距问题。

从去年7月版本开始图标改成了直接种在卡面上(可以找一找实卡，图标绝对位置是一致的)，然后文字用一个全角空格给图标留地方。

但字体间距是和字体本身挂钩的，文字大小也不是光靠改资源文件就可以调整的东西。

如果觉得不适应可以选择不使用隶书字体而使用官方本身提供的字体（之前已提供了可选项）

**Comment by ElapseRecall** [comment]
> 应该是字间距问题。
> 
> 从去年7月版本开始图标改成了直接种在卡面上(可以找一找实卡，图标绝对位置是一致的)，然后文字用一个全角空格给图标留地方。
> 
> 但字体间距是和字体本身挂钩的，文字大小也不是光靠改资源文件就可以调整的东西。
> 
> 如果觉得不适应可以选择不使用隶书字体而使用官方本身提供的字体（之前已提供了可选项）

感谢解惑，之前试过使用官方字体，后面发现部分卡片文本仍然存在溢出的情况，不过无伤大雅。
|01|02|
|---|---|
|![01](https://github.com/user-attachments/assets/eeb9a677-d0ab-4d32-b032-edc0a699c5da)|![02](https://github.com/user-attachments/assets/edb787b2-0827-4874-aed0-b7a66d4abf72)|
