### ISSUE TITLE
隶书卡名显示未适配“水龙星-赑屃”的“赑”字

### ISSUE THREAD

**Issue by MinYXn** [mikualpha/master-duel-chinese-switch#2]
可能是字库问题？

**Comment by MinYXn** [comment]
![1](https://github.com/mikualpha/master-duel-chinese-switch/assets/113080762/93728487-480b-4292-ab18-064f4874b390)
似乎屃字显示也有问题？

**Comment by MinYXn** [comment]
![2](https://github.com/mikualpha/master-duel-chinese-switch/assets/113080762/7dc9a115-75b2-4ff2-b241-302f2d0be33c)似乎“屃”字显示也有问题？

**Comment by mikualpha** [comment]
似乎不影响使用……先将就着吧(起码不像隔壁`魊影`那种禁发令直接GG的问题)，做一版隶书字体很费劲。。。
目前用的还是 @Timelic 之前做的字体，有时间统一换一个（看看能不能换成日文MD用的那个隶书）

**Comment by MinYXn** [comment]
十分感谢

**Comment by mikualpha** [comment]
今天查了一下，似乎**原版字体也没有这个字**，可能修复不了，除非整个换字体……
感觉并不是什么小工程，而且换成其它字体可能看习惯了日文版字体的玩家可能并不是很乐意
暂时先搁置此问题吧。。
