### ISSUE TITLE
[BUG] 目前遇到一個MD中文顯示Bug 只要安裝會改變卡片圖面的Mod 圖像顯示度會變低 文字解析度會變低 4K-1080P模式皆相同

### ISSUE THREAD

**Issue by Blessmea** [mikualpha/master-duel-chinese-switch#4]
僅需安裝成功Mod就會影響，目前Mod安裝正常，但是安裝完成後圖面與文字解析度皆為降低至無法清晰辨認的程度。

安裝前清晰圖面<a href="https://ibb.co/ZfvfbbK"><img src="https://i.ibb.co/mRdRPPt/20230715025408-1.jpg" alt="20230715025408-1" border="0"></a>

安裝後圖面<a href="https://ibb.co/5WLLD9S"><img src="https://i.ibb.co/qMppGnc/20230715025454-1.jpg" alt="20230715025454-1" border="0"></a>

切換語言版本替換掉圖面數據後即可恢復原始清晰度，希望開發者能解決這個問題，感謝。已嘗試過在1080P也會遇到相同情況 (圖片清晰度點開可清楚查看原始4K圖源大小，縮圖看起來差異不大)

目前無安裝任何其他圖形MOD，已經清除所有緩存所測試的結果。

版本:        MDTR_v1.6.0
版本	Windows 10 家用版
版本	22H2
OS 組建	19045.3208
體驗	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by mikualpha** [comment]
似乎是字体原因导致，可以检查一下日语界面下的情况（补丁与日语界面使用的是同一个字体）。
完全没有什么头绪……补丁只更新了文本文件和字体文件，按理不至于这样
------
另外如果对隶书字体没有什么特别追求的话，可以取消隶书字体安装选项，使用官方提供的楷体，变正常的概率会更大一点。

**Comment by MinYXn** [comment]
> 似乎是字体原因导致，可以检查一下日语界面下的情况（补丁与日语界面使用的是同一个字体）。
> 
> 完全没有什么头绪……补丁只更新了文本文件和字体文件，按理不至于这样
> 
> 另外如果对隶书字体没有什么特别追求的话，可以取消隶书字体安装选项，使用官方提供的楷体，变正常的概率会更大一点。

即使是楷体也完全没有解决，可能和字体无关。上个版本没有这样的bug，可以试着从这方面入手？

**Comment by mikualpha** [comment]
> 即使是楷体也完全没有解决，可能和字体无关。上个版本没有这样的bug，可以试着从这方面入手？

那只勾选安装翻译，把生僻字修复和隶书安装全取消了试试？
那样的话就完全不会安装字体文件了……
还不行那就真的神奇了……

**Comment by MinYXn** [comment]
> > 即使是楷体也完全没有解决，可能和字体无关。上个版本没有这样的bug，可以试着从这方面入手？
> 
> 那只勾选安装翻译，把生僻字修复和隶书安装全取消了试试？ 那样的话就完全不会安装字体文件了…… 还不行那就真的神奇了……
> 
> 和补丁版本似乎没有太大关系，1.6.0相对1.5.1没有字体层面的修改，只改了翻译逻辑。

无论切换日语，还是不勾选生僻字修复和隶书安装，bug都没有彻底解决（切换之后会恢复正常，但是退出后再进入还是有bug）。甚至切换回去翻译都重置了都解决不了，我在怀疑是不是游戏本身的bug了。不过切换一下画质再切换回去可以暂时恢复（当然重进游戏又会触发），可以试试从这入手

**Comment by mikualpha** [comment]
= =那这怎么入手法……感觉是比较底层的渲染逻辑了
鉴于现在游戏自己的BUG都不少，我建议是先观望一段时间……

**Comment by mikualpha** [comment]
本地无法复现，起码这边小字的字形还是看得清的，需要更多信息
![image](https://github.com/mikualpha/master-duel-chinese-switch/assets/24711249/d26657bd-28c6-4e66-9bdf-b6d4910fdda9)

**Comment by Blessmea** [comment]
嘗試一下我切成簡中會自動模糊，我先整個遊戲重新解除安裝後再嘗試吧，看起來應該是遊戲版本Bug...
MD昨天排連鎖也出問題，我先重新安裝看看。

**Comment by mikualpha** [comment]
本地以一种奇怪的方式复现了：楷体糊到爆炸，隶书啥事没有……
感觉还是官方客户端的渲染问题……
![image](https://github.com/mikualpha/master-duel-chinese-switch/assets/24711249/b7f50888-a75b-447f-b634-b659251ea93b)
![image](https://github.com/mikualpha/master-duel-chinese-switch/assets/24711249/ddb60fd5-76e7-4b4e-ae86-cc7d70bd490f)
