### ISSUE TITLE
[BUG] “超量对齐”的文本显示错误

### ISSUE THREAD

**Issue by MinYXn** [mikualpha/master-duel-chinese-switch#8]
**BUG描述**
新卡片“超量对齐”卡名与描述显示错误

**截图**
![masterduel 2023_8_30 9_26_09](https://github.com/mikualpha/master-duel-chinese-switch/assets/113080762/e810e25b-1ee3-4bff-9a22-c890c9f5c64c)目前“超量对齐”的卡名以及描述错误，显示为了与另一张“超量调换”相同的卡名和描述

**软件版本**
1.6.1

**Comment by mikualpha** [comment]
已在 #8 中回复
